name: Build Check

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Clone repository
      - uses: actions/checkout@v1
        with:
          #submodules: true
          fetch-depth: 1

      - name: Set up Go 1.13.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.1
        id: go


      - name: mod tidy
        run: go mod tidy -v

      - name: check basic
        run: cd examples/basic;windres -i ui/ui.rc -O coff -o ui.syso

      - name: build basic
        run: cd examples/basic;go generate -v;go build -v

      - name: check simple
        run:
          cd examples/simple;
          windres -i emptyProject/Debug/resource.res -O coff -o vsui.syso;
          go build -ldflags="-s -w -H windowsgui"

      - name: check wowjump
        run:
          cd examples/wowjump;
          windres -i ui/ui.rc -O coff -o ui.syso;
          go generate;
          go build -ldflags="-s -w -H windowsgui"

      - name: Pre-release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'whtiehack/wingui'
        run: |
          mkdir release
          Compress-Archive -CompressionLevel Optimal -Force -Path examples/basic/basic.exe -DestinationPath release/basic.zip
          Compress-Archive -CompressionLevel Optimal -Force -Path examples/simple/simple.exe -DestinationPath release/simple.zip
          Compress-Archive -CompressionLevel Optimal -Force -Path examples/wowjump/wowjump.exe -DestinationPath release/wowjump.zip

      - name: Draft Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'whtiehack/wingui'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            release/basic.zip
            release/simple.zip
            release/wowjump.zip
          draft: true