name: Build Check

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: testgcc
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        gcc -v
        echo "windres ~~~"
        windres -h


    - name: Build
      run: |
        go mod tidy -v
        cd examples/basic
        windres -i ui/ui.rc -O coff -o ui.syso
        go generate -v
        go build -v

