name: Build Check

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Set up Go 1.13.1
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.1
      id: go

    - name: testgcc
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        gcc -v
        echo "windres ~~~"
        windres -h


    - name: mod tidy
      run: go mod tidy -v

    - name: windres
      run: cd examples/basic | windres -i ui/ui.rc -O coff -o ui.syso

    - name: generate h file
      run: cd examples/basic | go generate -v

    - name: build exe file
      run: cd examples/basic | go build -v

