name: Build Check

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Go 1.13.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.1
        id: go


      - name: mod tidy
        run: go mod tidy -v

      - name: check basic
        run: cd examples/basic;windres -i ui/ui.rc -O coff -o ui.syso;go generate -v;go build -v;

      - name: check simple
        run:
          cd examples/simple;
          windres -i emptyProject/Debug/resource.res -O coff -o vsui.syso;
          go build -ldflags="-s -w -H windowsgui"

      - name: check wowjump
        run:
          cd examples/wowjump;
          windres -i ui/ui.rc -O coff -o ui.syso;
          go generate;
          go build -ldflags="-s -w -H windowsgui"

